repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format code with black
        entry: poetry run black
        args: [--line-length=88]
        types: [file, python]
        files: "^(src|tests)"
        language_version: python3.13
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        entry: poetry run isort
        files: "^(src|tests)"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: poetry run flake8
        args: ["--config=src/utils/.flake8"]
        files: "^(src|tests)"
